### ISSUE TITLE
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]]

### ISSUE THREAD

**Issue by Tato14** [livepeer/ai-worker#29]
Hi, I am getting this error when tried to run:

`docker run --gpus 0 -v ./models:/models livepeer/ai-runner:latest python bench.py --pipeline text-to-image --model_id stabilityai/stabilityai/sd-turbo`

Any idea why is this happening?
Thanks

**Comment by yondonfu** [comment]
@Tato14 

- What OS are you running?
- Do you have [nvidia-container-toolkit](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html) installed?

**Comment by Tato14** [comment]
Yes Ubuntu 22.04

I installed the nvidia-container-toolkit and the error still persists

**Comment by yondonfu** [comment]
@Tato14 Did you also try restarting Docker and/or restarting the machine? There seems to be some other recommendations (such as [this](https://askubuntu.com/questions/1258571/docker-only-works-with-nvidia-drivers-upon-reinstall)) from searching for "Error response from daemon: could not select device driver "" with capabilities: [[gpu]]" online that may be relevant depending on your configuration.

**Comment by Titan-Node** [comment]
@yondonfu @Tato14 
I got the benchmark to work with the [nvidia-container-toolkit](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html) installed just after I had the `with capabilities: [[gpu]]` issue.

I changed a few things at once.
1) Changed from Ubuntu 22 to 20 (not sure that helped)
2) Updated to Nvidia driver 551 (again not sure it helped but it was important as I tried with 535 with failure)
At this point I still got the `capabilities: [[gpu]]with capabilities: [[gpu]]` error
3) Installed the toolkit including the [experimental packages ](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html#configuring-docker) and [configured docker](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html#configuring-docker) and it works

**Comment by Tato14** [comment]
@yondonfu @Titan-Node I can confirm that worked with the changes mentioned earlier. To add on this, I used the Nvidia Driver 545.29.06 and Cuda version 12.3 on Ubuntu 22.
Thanks again for the great feedback!
