### ISSUE TITLE
Black bar at the bottom of downloaded images generated with the ByteDance model

### ISSUE THREAD

**Issue by papabear99** [livepeer/ai-worker#50]
### Describe the bug

Black bar visible at the bottom of downloaded images generated with the ByteDance model.  The same issue is also present when using the RealVis model but since it's not an "officially" supported model I have only included images generated using the ByteDance model.

If you are viewing this page in dark mode you can't see the issue.  Either download the images or switch to day mode.

![ByteCat](https://github.com/livepeer/ai-worker/assets/89408276/7f63b2e2-effc-4406-8a68-bc18738a318d)
![JasonTest](https://github.com/livepeer/ai-worker/assets/89408276/0701d7bc-17a4-471e-a996-073e39c053ca)
![BytePorsche](https://github.com/livepeer/ai-worker/assets/89408276/40bf1987-246c-4613-9c4e-d91863d234da)

### Reproduction steps

1. Go to any page that uses Livepeer's AI video to generate it's images i.e. https://letsgenerate.ai , https://inference.stronk.rocks , https://lpt-aivideo-playground-2fbb4d44077b.herokuapp.com
2. Generate an image using the ByteDance model
3. Download the image
4. View locally 

This can also be reproduced using a curl command to send and download an image from a Livepeer gateway.

### Expected behaviour

The image should not have the above mentioned black at the bottom

### Severity

None

### OS

Windows

### Running on

Docker

**Comment by rickstaa** [comment]
This was fixed in https://github.com/livepeer/go-livepeer/pull/3020e
